version: '3'

services:
  unchained:
    image: livingwithhippos/unchainedbot:0.1
    container_name: unchained
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN="1394243482:AAGiBV048tfEtq7CZIJ3YWFd1jkynD0rfRA"
      - PRIVATE_API_KEY="V3YWPVADJBHMM22YC4FPZJQIEU2O3KT23J45UCEYDFIUA"
    volumes:
      - ./downloads:/downloads
